/*
 * doxy-namespaces.h: This file exists as a place to document namespaces for doxygen. 
 *   It is never compiled, and is for reference only.
 * Copyright (C) 2012, Project Inglenook (http://www.project-inglenook.co.uk)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

//
// NOTE:
// This documents sole purpose is to provide a centeralised point
// for all namespaces to be documented in a manner in which doxygen
// (http://doxygen.org) will recognise. Doxygen is a tools used by 
// Inglenook to automtically generate HTML doumentation from inline 
// comments.
//
// 
// IMPORTANT:
// This document is never compiled and is not used in any binaries 
// generated by Inglenook
//


/// Root namespace for all inglenook code.
namespace inglenook
{

	/// Contains common application configuration logic and handling.
	namespace config
	{
	
		/// Logic for interaction with settings at application configuration scope.
		namespace app {}
		
		/// Logic for interacting with the settings cache (prevent unneccessary IO).
		namespace cache {}
		
		/// Logic for interaction with settings receieved from the command line.
		namespace command_line {}
		
		/// Exceptions specific to configuration logic.
		namespace exceptions {}
	
		/// Logic for interaction with settings at global configuration scope.
		namespace global {}
		
		/// Common confguration keys
		namespace keys {}
	
	}

	/// Contains code that is core to most, if not all, inglenook applications.
	namespace core 
	{
	
		/// Logic for interacting with the system environment.
		namespace environment
		{
		
			/// Logic for manipulating environment variables.
			namespace variables {}
		
		}
	
		/// Various exception definitiions (and related elements) used by many inglenook applications.
		namespace exceptions {}
	
	}
	
	/// Logic for directory reasoning (where *stuff* can be located).
	namespace directories {}
	
	/// Contains code related to the various logging tools and libraries within inglenook.
	namespace logging {}

}
